sudo: false
language: go
go:
  - "1.13.9"
  - "1.14.1"
  - master
git:
  depth: 1
install: go get -v github.com/gohugoio/hugo
script:
  hugo
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: public
  repo: monsterhxw/monsterhxw.github.io
#  fqdn: <custom-domain-if-needed>
  target_branch: master
  email: 770342643@qq.com
  name: monsterhxw
